title: Volland API Documentation
description: Documentation for the Volland API
theme: just-the-docs
#remote_theme: "pmarsceill/just-the-docs"

url: https://aureumai.github.io

nav_external_links:
  - title: Volland
    url: https://www.vol.land
    hide_icon: true

  - title: Volland Terms of Service
    url: https://www.vol.land/tos
    hide_icon: true

